#!/bin/bash
echo "current working directory is " && pwd

function yes_or_no {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0  ;;  
            [Nn]*) echo "Aborted" ; return  1 ;;
        esac
    done
}


#get sd card name
sudo fdisk -l | grep mmcblk #TODO: check if sd card exists and make name variable
SDCARD=mmcblk0
echo "found SD-CARD $SDCARD"

#download latest image
mkdir tmp
pushd tmp/
#check if an image file already exists, otherwise download the latest
FILE="rpi_latest.img"
if [ -f $FILE ];then
    echo "$FILE exists; skipping download process"
else
    echo Downloading latest RPI-lite image 
    #TODO: switch to torrenting
    wget -O rpi_latest.zip https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip
    unzip rpi_latest.zip
    rm rpi_latest.zip
    mv *.img rpi_latest.img
fi
popd

#yes_or_no "should i continue to writing the img?"

#flash image
echo "Writing image to SD-CARD"
sudo dd if=tmp/rpi_latest.img of=/dev/$SDCARD bs=4M status=progress

#unmount in case the system automounts partitions
sudo umount /dev/mmcblk0p1
sudo umount /dev/mmcblk0p2

#mount written partitions
sudo mkdir /mnt/rootfs
sudo mkdir /mnt/boot

sudo mount /dev/mmcblk0p1 /mnt/boot/
sudo mount /dev/mmcblk0p2 /mnt/rootfs/
echo "mounted partitions"

#enable ssh, WIFI
echo "copying config files..."
sudo touch /mnt/boot/ssh
#sudo cp conf/wpa_supplicant.conf /mnt/boot/wpa_supplicant.conf    #--------------use this template for wpa_supplicant.conf and add your WIFI credentials
sudo cp /home/$USER/.licenses/creds /mnt/boot/wpa_supplicant.conf

#copy config files to execute on the new system
sudo cp -r conf/ /mnt/rootfs/home/pi/
sudo cp 01_as_pi_user /mnt/rootfs/home/pi/
sudo cp 03_as_new_user /mnt/rootfs/home/pi/
#TODO: Autostart config scripts after first startup ; at the moment you have to start them manually

echo "everything done, cleaning up..."
sudo umount /dev/mmcblk0p1
sudo umount /dev/mmcblk0p2

yes_or_no "should i remove the tmp folder ?" && rm -rf tmp/
