#!/bin/bash

# this file is used for automatically making the fresh RPI installation secure
#set hostname
sudo cp conf/hostname /etc/hostname

# user
sudo adduser server
sudo usermod -a -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi server
sudo mv /home/pi/conf/ /home/server/
sudo mv /home/pi/as_new_user /home/server/
sudo mv /home/pi/software /home/server/

sudo reboot
