#!/bin/bash

echo "Removing user pi..."
sudo deluser -remove-home pi

#ssh
sudo rsync conf/sshd_config /etc/ssh/sshd_config

#networking
sudo apt install ufw -y
sudo ufw enable
sudo ufw allow 22
sudo ufw allow 80 
sudo ufw allow 3307 #mariaDB port (NextCloud DB) 
sudo ufw allow 8080 
sudo ufw allow 10000

sudo apt install fail2ban -y
sudo rsync conf/jail.local /etc/fail2ban/jail.local

#update
sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y

#install required dependencies for
sudo apt install apache2 php php-gd sqlite php-sqlite3 unzip php-curl php-zip php-xml php-mbstring php-imagick php7.3-intl php-common php7.3-common php7.3-bz2 libapache2-mod-php mariadb-server php-mysql libnet-ssleay-perl libauthen-pam-perl libio-pty-perl apt-show-versions net-tools nmap libnet-ssleay-perl libauthen-pam-perl libio-pty-perl perl-openssl-defaults -y

FILE="webmin_1.974_all.deb"
if [ -f $FILE ];then
    echo "$FILE exists; skipping download process"
else
    echo "Downloading WEBMIN...."
    wget https://downloads.sourceforge.net/project/webadmin/webmin/1.974/webmin_1.974_all.deb
fi
sudo dpkg -i webmin_1.974_all.deb
